sudo: required
language: minimal

services:
  - docker

before_install:
  - ./.travis/install_docker.sh

before_script:
  - docker-compose build app

script:
  - docker-compose run --rm app pytest -vv -n 3 --cov=.

after_script:
  - docker-compose down
