version: "3"

services:
  db:
    image: postgres:11.1
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .envs/.local/.postgres
    ports:
      - 5432:5432

  redis:
    image: redis:5
    hostname: redis
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

volumes:
  dbdata:
  redisdata:
