version: "3.7"

x-app: &app
  build: ./backend
  image: reactor_app
  env_file:
    - .envs/.production/app.env
    - .envs/.production/postgres.env
  volumes:
    - ./backups:/var/backups
  depends_on:
    - db
    - redis


services:
  db:
    image: postgres:11.1
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .envs/.production/postgres.env

  redis:
    image: redis:5
    hostname: redis
    volumes:
      - redisdata:/data

  nginx:
    build: ./nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
      - 5432:5432
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/usr/share/nginx/html
    depends_on:
      - app
      - db

  app:
    <<: *app
    command: ["./scripts/run.sh", "prod"]

  bot:
    <<: *app
    command: ["./manage.py", "runbot"]
    environment:
      - DJANGO_SETTINGS_MODULE=reactor.settings.bot

  scheduler:
    <<: *app
    command: ["python", "scheduler.py"]

volumes:
  dbdata:
  redisdata:
