version: "3.7"

x-app: &app
  env_file:
    - .envs/.local/app.env
    - .envs/.local/postgres.env
  volumes:
    - ./backend:/app

services:
  nginx:
    ports:
      - 443
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt
      - /usr/share/nginx/html

  db:
    env_file:
      - .envs/.local/postgres.env

  redis:
    ports:
      - 6379:6379

  app:
    <<: *app
    command: ["./scripts/run.sh", "dev"]
    environment:
      - DJANGO_SETTINGS_MODULE=reactor.settings.base
    ports:
      - 8000:8000

  bot:
    <<: *app
