version: "3.7"

x-app: &app
  build: ./backend
  image: reactor_app
  env_file:
    - .envs/.production/app.env
    - .envs/.production/postgres.env


services:
  db:
    image: postgres:11.1
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .envs/.production/postgres.env

  redis:
    image: redis:5
    hostname: redis
    volumes:
      - redisdata:/data

  app:
    <<: *app
    command: ["./scripts/run.sh", "prod"]
    depends_on:
      - db
      - redis

  bot:
    <<: *app
    command: ["./manage.py", "runbot"]
    environment:
      - DJANGO_SETTINGS_MODULE=reactor.settings.bot
    depends_on:
      - db
      - redis

volumes:
  dbdata:
  redisdata:
