version: "3.7"

x-app: &app
  env_file:
    - .envs/.local/app.env
    - .envs/.local/postgres.env
  volumes:
    - ./backend:/app

services:
  db:
    ports:
      - 5432:5432
    env_file:
      - .envs/.local/postgres.env

  redis:
    ports:
      - 6379:6379

  app:
    <<: *app
    command: ["./scripts/run.sh", "dev"]
    ports:
      - 8000:8000

  bot:
    <<: *app
